#!/usr/bin/env python3
"""Generate the C channel table, CAN decoder and RaceStudio sheet from channels.yaml.

One source of truth for both ends of the wire. Without this, someone nudges a
scaling factor in RaceStudio eighteen months from now and oil pressure reads
10x with nobody able to say why.

Usage:  tools/gen_channels.py [--check]
        --check  exit non-zero if the generated files are out of date
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "config" / "channels.yaml"
GEN = ROOT / "src" / "app" / "generated"
DOCS = ROOT / "docs"

BANNER = "/* GENERATED by tools/gen_channels.py from config/channels.yaml. DO NOT EDIT. */"


def load():
    with SPEC.open() as f:
        spec = yaml.safe_load(f)
    for key in ("bus", "channels", "frames", "pages"):
        if key not in spec:
            sys.exit(f"channels.yaml: missing top-level '{key}'")
    return spec


def validate(spec):
    """Catch the mistakes that would otherwise surface as a wrong number at 180mph."""
    errors = []
    ids = [c["id"] for c in spec["channels"]]
    for dup in {i for i in ids if ids.count(i) > 1}:
        errors.append(f"duplicate channel id '{dup}'")

    known = set(ids)
    seen_frames = set()
    for fr in spec["frames"]:
        if fr["id"] in seen_frames:
            errors.append(f"duplicate frame id 0x{fr['id']:03X}")
        seen_frames.add(fr["id"])

        used = {}
        for sig in fr["signals"]:
            if sig["channel"] not in known:
                errors.append(f"frame {fr['name']}: unknown channel '{sig['channel']}'")
            size = sig.get("size", 16) // 8
            off = sig["offset"]
            if off + size > 8:
                errors.append(f"frame {fr['name']}: '{sig['channel']}' runs past byte 8")
            for b in range(off, off + size):
                if b in used:
                    errors.append(
                        f"frame {fr['name']}: byte {b} claimed by both "
                        f"'{used[b]}' and '{sig['channel']}'"
                    )
                used[b] = sig["channel"]

    for pg in spec["pages"]:
        for ch in pg.get("channels", []) + pg.get("extra", []):
            if ch not in known:
                errors.append(f"page {pg['id']}: unknown channel '{ch}'")

    if spec["bus"].get("mode") != "listen_only":
        errors.append("bus.mode must be listen_only — the dash never transmits")

    if errors:
        for e in errors:
            print(f"error: {e}", file=sys.stderr)
        sys.exit(1)


def c_enum(spec):
    out = [BANNER, "#pragma once", "", "typedef enum {"]
    for i, ch in enumerate(spec["channels"]):
        out.append(f"    CH_{ch['id'].upper()} = {i},")
    out.append(f"    CH_COUNT = {len(spec['channels'])}")
    out.append("} channel_id_t;")
    out.append("")
    return "\n".join(out)


def c_table(spec):
    out = [BANNER, '#include "channel_table.h"', "", "const channel_desc_t CHANNEL_DESC[CH_COUNT] = {"]
    for ch in spec["channels"]:
        a = ch.get("alarms", {}) or {}

        def bound(key, fallback):
            return f"{a[key]:.6f}f" if key in a else fallback

        out.append(
            "    [CH_{ID}] = {{ .name = \"{id}\", .label = \"{label}\", .unit = \"{unit}\","
            " .scale = {scale:.6f}f, .offset = {off:.6f}f, .decimals = {dec},"
            " .timeout_ms = {to}, .group = \"{group}\","
            " .warn_lo = {wl}, .warn_hi = {wh}, .crit_lo = {cl}, .crit_hi = {ch_} }},".format(
                ID=ch["id"].upper(),
                id=ch["id"],
                label=ch["label"],
                unit=ch.get("unit", ""),
                scale=float(ch.get("scale", 1.0)),
                off=float(ch.get("offset", 0.0)),
                dec=ch.get("decimals", 0),
                to=ch.get("timeout_ms", 1000),
                group=ch.get("group", ""),
                wl=bound("warn_lo", "-INFINITY"),
                wh=bound("warn_hi", "INFINITY"),
                cl=bound("crit_lo", "-INFINITY"),
                ch_=bound("crit_hi", "INFINITY"),
            )
        )
    out.append("};")
    out.append("")
    return "\n".join(out)


def c_table_header(spec):
    return "\n".join([
        BANNER,
        "#pragma once",
        "",
        "#include <math.h>",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        '#include "channel_ids.h"',
        "",
        "/* Static description of a channel. Flash-resident, never mutated. */",
        "typedef struct {",
        "    const char *name;",
        "    const char *label;",
        "    const char *unit;",
        "    float scale;",
        "    float offset;",
        "    uint8_t decimals;",
        "    uint16_t timeout_ms;",
        "    const char *group;",
        "    float warn_lo, warn_hi, crit_lo, crit_hi;",
        "} channel_desc_t;",
        "",
        "/* Live value. Written only by the CAN handler, read only by the",
        " * renderer via channel_snapshot(). */",
        "typedef struct {",
        "    int32_t raw;",
        "    uint32_t last_rx_ms;",
        "    bool ever_seen;",
        "} channel_value_t;",
        "",
        "extern const channel_desc_t CHANNEL_DESC[CH_COUNT];",
        "",
        f"#define CAN_BITRATE {spec['bus']['bitrate']}u",
        f"#define CAN_FRAME_COUNT {len(spec['frames'])}u",
        "",
    ])


def c_decoder(spec):
    out = [
        BANNER,
        '#include "channel_table.h"',
        "",
        "/* Written by can_on_frame() only. A load and a shift, never a parser. */",
        "extern channel_value_t g_channel[CH_COUNT];",
        "",
        "static inline int32_t rd16le(const uint8_t *d, int off) {",
        "    return (int32_t)(int16_t)((uint16_t)d[off] | ((uint16_t)d[off + 1] << 8));",
        "}",
        "",
        "static inline int32_t rd16be(const uint8_t *d, int off) {",
        "    return (int32_t)(int16_t)(((uint16_t)d[off] << 8) | (uint16_t)d[off + 1]);",
        "}",
        "",
        "static inline void store(channel_id_t id, int32_t raw, uint32_t now_ms) {",
        "    g_channel[id].raw = raw;",
        "    g_channel[id].last_rx_ms = now_ms;",
        "    g_channel[id].ever_seen = true;",
        "}",
        "",
        "/* Returns true if the frame was one of ours. Unknown IDs are ignored,",
        " * so other traffic on the bus costs a switch miss and nothing else. */",
        "bool can_on_frame(uint32_t id, const uint8_t *d, uint8_t dlc, uint32_t now_ms) {",
        "    switch (id) {",
    ]
    for fr in spec["frames"]:
        rd = "rd16be" if fr.get("endian", "little") == "big" else "rd16le"
        need = max(s["offset"] + s.get("size", 16) // 8 for s in fr["signals"])
        out.append(f"    case 0x{fr['id']:03X}: /* {fr['name']} @ {fr['rate_hz']}Hz */")
        out.append(f"        if (dlc < {need}) return false;")
        for sig in fr["signals"]:
            out.append(
                f"        store(CH_{sig['channel'].upper()}, "
                f"{rd}(d, {sig['offset']}), now_ms);"
            )
        out.append("        return true;")
    out += [
        "    default:",
        "        return false;",
        "    }",
        "}",
        "",
    ]
    return "\n".join(out)


def racestudio_sheet(spec):
    bus = spec["bus"]
    lines = [
        "# RaceStudio 3 — PDM32 custom CAN output stream",
        "",
        "GENERATED from `config/channels.yaml`. Do not hand-edit; regenerate with",
        "`tools/gen_channels.py`.",
        "",
        f"- **Bitrate:** {bus['bitrate']} bit/s",
        "- **ID format:** standard 11-bit",
        "- **Byte order:** little-endian unless a frame says otherwise",
        "- **All signals:** 16-bit signed, byte-aligned, no multiplexing",
        "",
        "The dash is configured listen-only and never transmits, so nothing here",
        "needs an inbound path on the PDM.",
        "",
        "## Reserved ID blocks",
        "",
        "| Block | Range | Nominal rate | Contents |",
        "|-------|-------|--------------|----------|",
    ]
    for name, blk in bus["id_blocks"].items():
        lo, hi = blk["range"]
        lines.append(
            f"| {name} | 0x{lo:03X}–0x{hi:03X} | {blk['rate_hz']} Hz | {blk['note']} |"
        )

    lines += ["", "## Frames", ""]
    by_id = {c["id"]: c for c in spec["channels"]}
    total_bits = 0
    for fr in spec["frames"]:
        lines += [
            f"### 0x{fr['id']:03X} — {fr['name']} @ {fr['rate_hz']} Hz",
            "",
            "| Byte | Channel | Label | Unit | Scale | Decimals |",
            "|------|---------|-------|------|-------|----------|",
        ]
        for sig in fr["signals"]:
            ch = by_id[sig["channel"]]
            off = sig["offset"]
            lines.append(
                f"| {off}–{off + 1} | `{ch['id']}` | {ch['label']} | "
                f"{ch.get('unit') or '—'} | {ch.get('scale', 1.0)} | {ch.get('decimals', 0)} |"
            )
        lines.append("")
        # Worst-case standard 8-byte frame incl. stuffing ~ 130 bits.
        total_bits += 130 * fr["rate_hz"]

    load = 100.0 * total_bits / bus["bitrate"]
    lines += [
        "## Bus budget",
        "",
        f"Worst case (full 8-byte frames, maximum bit stuffing): **~{load:.1f}% "
        f"of {bus['bitrate'] // 1000} kbit/s**.",
        "",
        "Plenty of headroom. Add channels in the appropriate ID block rather than",
        "repacking existing frames.",
        "",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if generated files are stale")
    args = ap.parse_args()

    spec = load()
    validate(spec)

    artifacts = {
        GEN / "channel_ids.h": c_enum(spec),
        GEN / "channel_table.h": c_table_header(spec),
        GEN / "channel_table.c": c_table(spec),
        GEN / "can_decode.c": c_decoder(spec),
        DOCS / "RACESTUDIO.md": racestudio_sheet(spec),
    }

    stale = []
    for path, content in artifacts.items():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        stale.append(path.relative_to(ROOT))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)

    if args.check and stale:
        print("stale generated files:", file=sys.stderr)
        for p in stale:
            print(f"  {p}", file=sys.stderr)
        print("run tools/gen_channels.py", file=sys.stderr)
        return 1

    digest = hashlib.sha256(SPEC.read_bytes()).hexdigest()[:12]
    verb = "up to date" if not stale else f"wrote {len(stale)} file(s)"
    print(f"{verb} — {len(spec['channels'])} channels, {len(spec['frames'])} frames, "
          f"{len(spec['pages'])} pages (spec {digest})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
